version: "3"
services:
  reverseproxy:
      image: udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-api-user
        - udagram-api-feed
  udagram-api-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://a2be403475fe142e688701bf612a4af1-1094786878.us-east-1.elb.amazonaws.com:8100"
  udagram-api-feed:
    image: udagram-api-feed
    volumes:
      - "C:/Users/darwi/.aws:/root/.aws"
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://a2be403475fe142e688701bf612a4af1-1094786878.us-east-1.elb.amazonaws.com:8100"
  frontend:
    image: udagram-frontend
    ports:
      - "8100:80"